name: slidy_e_modular
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.2
  mobx: ^2.0.7
  flutter_mobx: ^2.0.5
  build_runner: ^2.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  mobx_codegen: ^2.0.6
  modular_test: ^2.0.0

flutter:
  uses-material-design: true

scripts:
  print: echo Reuel
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch --delete-conflicting-outputs
  clean: flutter pub run build_runner clean 
  compilar: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
  profile: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi --profile
